In [1]:
# 캐글의 **Mall Customer Segmentation Data**를 사용하시오.
# - Spending Score 값을 기준으로 아래와 같이 고객 등급(label)을 생성하시오.
# (if문으로 함수구현 - 함수명: def create_label(score))
# 1 ~ 33 : Low (0)
# 34 ~ 66 : Medium (1)
# 67 ~ 100 : High (2)
# - 필요한 전처리 작업과 표준화작업, 학습용/테스트용으로(20%) 분리하시오.
# - 입력층 구성 후 은닉층 2개 이상
# - ReLU 사용 / 출력층 생성
# - 필요한 손실함수 주고 , Optimizer는  Adam
# - 테스트 데이터로 실제 등급과 예측 등급이 얼마나 일치하는지 정확도(Accuracy)를 출력
# ⇒ 정확도 출력(mode.eval () - with no grad() : 안에 정확도 출력 )

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('./Mall_Customers.csv')
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [16]:
# - Spending Score 값을 기준으로 아래와 같이 고객 등급(label)을 생성하시오.
# (if문으로 함수구현 - 함수명: def create_label(score))
# 1 ~ 33 : Low (0)
# 34 ~ 66 : Medium (1)
# 67 ~ 100 : High (2)
def create_label(score):
    labels = []
    if score>=67:
        labels.append('2')
    elif score>=34:
        labels.append('1')
    else:
        labels.append('0')
    return labels

In [32]:
epochs=len(df['Spending Score (1-100)'])
label=[]
for epoch in range(epochs):
    label.append(create_label(df['Spending Score (1-100)'][epoch]))

y=label

In [30]:
df.isna().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2  Female   21                  15                      81
2             3     NaN   20                  16                       6
3             4     NaN   23                  16                      77
4             5     NaN   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196     NaN   35                 120                      79
196         197     NaN   45                 126                      28
197         198     NaN   32                 126                      74
198         199     NaN   32                 137                      18
199         200     NaN   30                 137                      83

[200 rows x 5 columns]

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [36]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ValueError: could not convert string to float: 'Female'